---
deployment:
  tasks:
    - export DEPLOYMENTPATH=/home/user/public_html
    - /bin/cp -R css $DEPLOYMENTPATH
    - /bin/cp -R img $DEPLOYMENTPATH
    - /bin/cp -R js $DEPLOYMENTPATH
    - /bin/cp index.html $DEPLOYMENTPATH